global using Xunit;
global using Moq;
global using Microsoft.Extensions.Logging;
global using ProjetScolariteSOLID.Domain.Models;
global using ProjetScolariteSOLID.Domain.Repositories;
global using ProjetScolariteSOLID.Application.Contracts;
global using ProjetScolariteSOLID.Application.Services;
global using ProjetScolariteSOLID.Application.Validators;
global using ProjetScolariteSOLID.Tests.Fixtures;
